q3demotube/urls.py
from django.conf.urls.defaults import *
from q3demotube.models import Demo, Video
#from django.views.generic.create_update import delete_object
# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

video_dict = {
    'model': Video,
    'post_delete_redirect': '/q3demotube/demo_list/'
}

urlpatterns = patterns('',
    (r'^videos/$', 'q3demotube.views.videos'),
    (r'^videos/(?P<page_number>\d+)/$', 'q3demotube.views.videos'),
    (r'^my_videos/$', 'q3demotube.views.my_videos'),
    (r'^my_videos/(?P<page_number>\d+)/$', 'q3demotube.views.my_videos'),
    (r'^video/(?P<video_id>\d+)/$', 'q3demotube.views.video'),
    (r'^video_edit/(?P<video_id>\d+)/$', 'q3demotube.views.video_edit'),
    (r'^delete_video/(?P<object_id>\d+)/$', 'q3demotube.views.delete_video'),
    (r'^rate_video/$', 'q3demotube.views.rate_video'),
    (r'^add_demo/$', 'q3demotube.views.add_demo'),
    (r'^demo_list/$', 'q3demotube.views.demo_list'),
    (r'^demo/(?P<demo_id>\d+)/$', 'q3demotube.views.demo_view'),
    (r'^edit_demo/(?P<demo_id>\d+)/$', 'q3demotube.views.demo_view'),
    (r'^add_time/(?P<demo_id>\d+)/$', 'q3demotube.views.add_time'),
    (r'^delete_demo/(?P<object_id>\d+)/$', 'q3demotube.views.delete_demo'),
    (r'^get_images/(?P<demo_id>\d+)/$', 'q3demotube.views.get_images'),
    (r'^get_videos/(?P<demo_id>\d+)/$', 'q3demotube.views.get_videos'),
    (r'^edit_time/(?P<video_id>\d+)/$', 'q3demotube.views.edit_time'),
    (r'^add_favorite/$', 'q3demotube.views.add_favorite'),
    (r'^.*$', 'q3demotube.views.videos'),
)

urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^prviDjango/', include('prviDjango.foo.urls')),

    # Uncomment the next line to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line for to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    (r'^polls/', include('polls.urls')),
    (r'^lottery/', include('lottery.urls')),
    (r'^registration/', include('registration.urls')),
    (r'^q3demotube/', include('q3demotube.urls')),
    (r'^threadedcomments/', include('threadedcomments.urls')),
)

q3demotube/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=100)
    parent_cat = models.ForeignKey('self', null=True)
    user = models.ForeignKey(User, null=True)
    is_private = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

class Demo(models.Model):
    category = models.ForeignKey(Category)
    user = models.ForeignKey(User)
    name = models.CharField(max_length=200, blank=True)
    demo = models.FileField(upload_to='q3/demos')
    time_addet = models.DateTimeField(default=datetime.datetime.now)

    def __unicode__(self):
        return self.name

class Video(models.Model):
    demo = models.ForeignKey(Demo)
    name = models.CharField(max_length=200, blank=True)
    videoFile = models.FileField(upload_to='q3/videos')
    thumbnail = models.ImageField(upload_to='q3/thumbnails')
    bigImage = models.ImageField(upload_to='q3/images', null=True)
    description = models.TextField(blank=True)
    time = models.TimeField()
    start = models.TimeField(null=True)
    end = models.TimeField(null=True)
    duration = models.TimeField(null=True)
    capture_time = models.FloatField(null=True)
    compression_time = models.FloatField(null=True)
    has_images = models.BooleanField()
    has_video = models.BooleanField()
    time_addet = models.DateTimeField(default=datetime.datetime.now)
    view_count = models.PositiveIntegerField(default=0)
    rate = models.PositiveIntegerField(default=5)


    def __unicode__(self):
        return "%s - %s" % (self.name, self.time)

    def can_be_captured(self):
        return (self.end.minute * 60 + self.end.second) - (self.start.minute * 60 + self.start.second) <=  30

    def set_tags(self, tags):
        for t in self.tag_set.all():
            t.delete()
        for tag in tags.split(","):
            self.tag_set.create(tag=tag.strip())

    def tags(self):
        return ", ".join([t.tag for t in self.tag_set.all()])

class Tag(models.Model):
    video = models.ForeignKey(Video)
    tag = models.SlugField()

class View(models.Model):
    video = models.ForeignKey(Video)
    user = models.ForeignKey(User, null=True)
    ip = models.IPAddressField()
    time_addet = models.DateTimeField(default=datetime.datetime.now)

class Favorite(models.Model):
    user = models.ForeignKey(User)
    video = models.ForeignKey(Video)

    def __unicode__(self):
        return "%s -> %s" % (self.user.username, self.video.name)

class VideoRating(models.Model):
    user = models.ForeignKey(User)
    video = models.ForeignKey(Video)
    rate = models.IntegerField()


q3demotube/forms.py
from q3demotube.models import Demo, Video, VideoRating
from django import forms
from django.forms import ModelForm
from django import forms

class DemoForm(ModelForm):
    class Meta:
        model = Demo
        exclude = ('user', 'time_addet', 'view_count', 'rate', 'duration')

class DemoEdit(ModelForm):
    class Meta:
        model = Demo
        exclude = ('user', 'time_addet', 'demo', 'view_count', 'rate', 'duration')


class VideoForm(ModelForm):
    class Meta:
        model = Video
        fields = ('time', 'name',)
    tags = forms.CharField(max_length=300, min_length=2)

class VideoEdit(ModelForm):
    class Meta:
        model = Video
        fields = ('time', 'name', 'description')
    tags = forms.CharField(max_length=300, min_length=2)

class VideoRatingForm(ModelForm):
    class Meta:
        model = VideoRating
        fields = ('video', 'rate',)

class VideoTimeForm(ModelForm):
    class Meta:
        model = Video
        fields = ('start', 'end',)

q3demotube/views.py
from q3demotube.models import Demo, Video, Category
from q3demotube.forms import *
from django.shortcuts import render_to_response
from django.http import HttpResponse
from django.forms.formsets import formset_factory
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.template import RequestContext
from django.views.generic.simple import direct_to_template
from django.conf import settings
from q3demotube.q3demo import addSec, getSec, getMMEImages, getMMEVideos
from django.views.generic.create_update import delete_object
from common.SortHeaders import SortHeaders

@login_required
def add_demo(request):
    VideoFormSet = formset_factory(VideoForm, extra=3)
    if request.method == "POST":
        demoForm = DemoForm(request.POST, request.FILES) #, initial={'user_id': request.user.id}
        videoForm = VideoFormSet(request.POST)

        if demoForm.is_valid():
            d = demoForm.save(commit=False)
            d.user_id = request.user.id
            d.save()
            #>>> for t in v.tag_set.all():
            #...     t.delete()
            for f in videoForm.forms:
                if f.is_valid():
                    if 'time' in f.cleaned_data and 'tags' in f.cleaned_data:
                        name, timeIn = f.cleaned_data['name'], f.cleaned_data['time']
                        start, end = addSec(timeIn, -10), addSec(timeIn, 8)
                        video = d.video_set.create(name=name, time=timeIn, start=start, end=end, duration=addSec(end, - getSec(start)))
                        # Tags
                        video.set_tags(f.cleaned_data['tags'])
                        #for tag in f.cleaned_data['tags'].split(","):
                            #video.tag_set.create(tag=tag.strip())
        else:
            return direct_to_template(request, 'q3demotube/add_demo.html', { 'demoForm':demoForm, 'videoForm':videoForm})

    demoForm = DemoForm({'category': Category.objects.latest('id').id})
    videoForm = VideoFormSet()
    return direct_to_template(request, 'q3demotube/add_demo.html', { 'demoForm':demoForm, 'videoForm':videoForm})

@login_required
def demo_list(request):
    LIST_HEADERS = [("Name", "name"),  ("Demo", "demo"),  ("Category", "category__name"),
                        ("Date", "time_addet"),  ("User", "user__username"),  ("#Frags", None),
                        ("#Edit", None),  ("#Delete", None)]

    sort_headers = SortHeaders(request, LIST_HEADERS)
    demos = Demo.objects.filter(user=request.user).order_by(sort_headers.get_order_by())
    return direct_to_template(request, 'q3demotube/demo_list.html', {'demos': demos, 'headers': list(sort_headers.headers())})

@login_required
def demo_view(request, demo_id):
    demo = Demo.objects.get(pk=demo_id, user=request.user)
    if request.method == 'POST':
        demoEdit = DemoEdit(request.POST, instance=demo)
        if demoEdit.is_valid():
            demoEdit.save()
            return demo_list(request)

    videos = demo.video_set.all()
    demoEdit = DemoEdit(instance=demo)
    return direct_to_template(request, 'q3demotube/demo.html', {'videos': videos,
                                                        'demo': demo, 'demoEdit': demoEdit})

@login_required
def delete_demo(request, object_id):
    if Demo.objects.get(pk=object_id, user=request.user):
        return delete_object(request, object_id=object_id, model=Demo, post_delete_redirect='/q3demotube/demo_list/')

@login_required
def delete_video(request, object_id):
    video = Video.objects.get(pk=object_id, demo__user=request.user)
    if video:
        return delete_object(request, object_id=object_id, model=Video, post_delete_redirect='/q3demotube/demo/%s/' % video.demo.id)

def videos(request, page_number=1):
    LIST_HEADERS = [("name", "name"), ("duration", "duration"), ("time_addet", "time_addet"),
                    ("view_count", "view_count"), ("rate", "rate"), ("capture_time", "capture_time")]

    sort_headers = SortHeaders(request, LIST_HEADERS)
    videos = Video.objects.filter(has_video=True).order_by(sort_headers.get_order_by())
    p = Paginator(videos, 9)
    return direct_to_template(request, 'q3demotube/videos.html', {'videos': p.page(page_number).object_list,
                                'pages': p.num_pages,
                                'page_number': int(page_number), 'headers': list(sort_headers.headers())})


@login_required
def my_videos(request, page_number=1):
    videos = Video.objects.filter(has_video=True, demo__user=request.user).order_by('-time_addet')
    p = Paginator(videos, 9)
    return direct_to_template(request, 'q3demotube/my_videos.html', {'videos': p.page(page_number).object_list,
                                                            'pages': p.num_pages,
                                                            'page_number': int(page_number)})

def video(request, video_id):
    video = Video.objects.get(pk=video_id)
    video.view_set.create(ip=request.META['REMOTE_ADDR'], user_id=request.user.id)
    video.view_count += 1
    video.save()
    return direct_to_template(request, 'q3demotube/video.html', {'video': video,
                                'ratings': range(1,6), 'rated': video.rate})

@login_required
def video_edit(request, video_id):
    video = Video.objects.get(pk=video_id, demo__user=request.user.id)
    if request.method == 'POST':
        videoEdit = VideoEdit(request.POST, instance=video, initial={'tags': video.tags()})
        if videoEdit.is_valid():
            v = videoEdit.save()
            v.set_tags(videoEdit.cleaned_data['tags'])

        return direct_to_template(request, 'q3demotube/video_edit.html', {'videoEdit': videoEdit, 'video': video})
    else:
        videoEdit = VideoEdit(instance=video, initial={'tags': video.tags()})
        return direct_to_template(request, 'q3demotube/video_edit.html', {'videoEdit': videoEdit, 'video': video})

@login_required
def rate_video(request):
    if request.POST:
        video_id, rate = request.POST['object_id'], int(request.POST['rate'])
        video = Video.objects.get(pk=video_id)
        if rate in range(1,11) and not video.videorating_set.filter(user=request.user.id).count():
            video.videorating_set.create(rate=rate, user_id=request.user.id)
            video.rate = (video.rate + rate) / 2
            video.save()
            return HttpResponse("Video has been rated")
        return HttpResponse("Already voted!")
    return HttpResponse("Post Needet!")

@login_required
def add_favorite(request):
    from q3demotube.models import Favorite
    if request.method == "POST":
        f = Favorite(user_id=request.user.id, video_id=request.POST['video_id'])
        f.save()
        return HttpResponse("Favorite addet!")
    return HttpResponse("No!")

@login_required
def edit_time(request, video_id=0):
    video = Video.objects.get(pk=video_id, demo__user=request.user.id)
    start = addSec(video.time, -15)

    if request.method == "POST":
        timeForm = VideoTimeForm(request.POST, instance=video)
        if timeForm.is_valid():
            print "Is valid"
            t = timeForm.save(commit=False)
            t.duration = addSec(t.end, - getSec(t.start))
            t.save()
        return demo_view(request, video.demo_id)
    else:
        timeForm = VideoTimeForm({'start': video.start, 'end': video.end})

    images = [(str(addSec(start, i / 4)), "0" * (10 - len(str(i))) + str(i)) for i in range(140)]

    return direct_to_template(request, 'q3demotube/edit_time.html', {'images': images,
                                                            'demo_id': video.demo.id, 'timeForm': timeForm,
                                                            'videoTime': str(video.time), 'video': video})

@login_required
def add_time(request, demo_id=-1):
    d = Demo.objects.get(pk=demo_id, user=request.user.id)

    if request.method == "POST":
        videoForm = VideoForm(request.POST)
        if videoForm.is_valid():
            name, timeIn = videoForm.cleaned_data['name'], videoForm.cleaned_data['time']
            start, end = addSec(timeIn, -10), addSec(timeIn, 8)
            video = d.video_set.create(name=name, time=timeIn, start=start, end=end, duration=addSec(end, - getSec(start)))
            # Tags
            video.set_tags(videoForm.cleaned_data['tags'])
        return demo_view(request, demo_id)
    else:
        videoForm = VideoForm()
        return direct_to_template(request, 'q3demotube/add_time.html', {'demo_id': demo_id, 'videoForm': videoForm})

@login_required
def get_images(request, demo_id):
    demo = Demo.objects.get(pk=demo_id)
    if demo.video_set.filter(has_images=False).count():
        getMMEImages(demo_id)
    return demo_view(request, demo_id)

@login_required
def get_videos(request, demo_id):
    demo = Demo.objects.get(pk=demo_id)
    if demo.video_set.filter(has_video=False).count():
        getMMEVideos(demo_id)
    return demo_view(request, demo_id)


templates/q3demotube/add_demo.html
{% extends "q3demotube/baseq3.html" %}

{% block page_title %}Add Demo{% endblock %}
{% block content %}
<script language="javascript" type="text/javascript">
String.prototype.sprintf = function() { var i = 0, args = arguments[0]; return this.replace(/%s/g, function() { return args[i++] }); };

function setNameAndTimes() {
    //DEMO NAME
    demo = $('#id_demo').val()
    name = demo.replace(/^\d+\-/, "")
    name = name.split("__")[0]
    name = name.split("_")
    if(name.length > 0) {
        $('#id_name').val(name.join("_"))
    }

    videoName = name.join(" ")

    //TAGS
    tags = []
    for(i in name) {
        t = name[i].replace(/[^\d\w_\-]/, "")
        if(t.length > 2) {
            tags.push(t)
        }
    }
    tags = tags.join(", ")
    //TIMES
    times = demo.split("__")
    if(times.length > 1) {
        times = times[1].split("_")

        for(t in times) {
            $('#id_form-'+t+'-time').val("00:%s:%s".sprintf(times[t].split(".")))
            $('#id_form-'+t+'-name').val(videoName)
            $('#id_form-'+t+'-tags').val(tags)
        }
    }
}

$(document).ready(function(){
  $('#id_demo').change(setNameAndTimes)
 });


</script>

<form action="/q3demotube/add_demo/" method="POST" enctype="multipart/form-data">
    {{ demoForm.as_p }}
    <div>
        {{ videoForm.management_form }}
        Frags (time and tags requeired):<br/>
        Format: <b>00:00:00 hours:minutes:seconds</b><br/>
        {% for form in videoForm.forms  %}
            Name: {{ form.name }} Time :{{ form.time }} Tags: {{ form.tags }} <br/>
        {% endfor %}
    </div>
<input type="Submit" value="Submit">
</form>
{% endblock %}

templates/q3demotube/baseq3.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/lib/jquery-1.2.6.js"></script>
    <link rel="stylesheet" href="{{ MEDIA_URL }}q3/css/q3demotube.css" />
    <title>{% block title %}Quake 3 Demo Tube !!!{% endblock %}</title>
</head>

<body>
    <a href="/q3demotube/videos/"><h2>Quake 3 Demo Tube</h2></a>
    <hr/>
    <h3>{% block page_title %}Home{% endblock %}</h3>
    <hr/>
    <p id="menu">
        {% block menu %}

                <a href="/q3demotube/videos/1/0/">Videos</a>
                {% if user.is_authenticated %}
                    <a href="/q3demotube/my_videos/">My videos</a>
                    <a href="/q3demotube/demo_list/">My demos</a>
                    <a href="/q3demotube/add_demo/">Add Demo</a>
                    <a href="/registration/logout/">LogOut</a>
                    <b>Hi {{ user.username }}</b>
                {% else %}
                    <a href="/registration/login/">LogIn</a>
                    <a href="/registration/register/">Register</a>
                {% endif %}


        {% endblock %}
    </p>
    <hr/>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/q3demotube/demo.html
{% extends "q3demotube/baseq3.html" %}

{% block page_title %}Demo View{% endblock %}
{% block content %}
<p>
<form action="/q3demotube/edit_demo/{{ demo.id }}/" method="POST" enctype="multipart/form-data">
{{ demoEdit.as_p }}
<input type="Submit" value="Submit"><br/>
</form>
</p><br/>

<b>Frag List:</b><br/>
<table border="1">
<tr>
    <th><b>Name</b></th>
    <th><b>Time</b></th>
    <th><b>Start</b></th>
    <th><b>End</b></th>
    <th><b>Description</b></th>
    <th><b>Tags</b></th>
    <th><b>Has_images</b></th>
    <th><b>Has_video</b></th>
    <th><b>Can be captured</b></th>
    <th><b>#Edit</b></th>
    <th><b>#Edit times</b></th>
    <th><b>Delete</b></th>
</tr>
{% for v in videos  %}
<tr>
    <td> {{ v.name }}</td>
    <td> {{ v.time }}</td>
    <td> {{ v.start }}</td>
    <td> {{ v.end }}</td>
    <td> {{ v.description }}</td>
    <td> {{ v.tags }}</td>
    <td> {{ v.has_images }}</td>
    <td> {{ v.has_video }}</td>
    <td> {{ v.can_be_captured }}</td>
    <td> <a href="/q3demotube/video_edit/{{ v.id }}/">[$]</a></td>
    <td> <a href="/q3demotube/edit_time/{{ v.id }}/">[$]</a></td>
    <td> <a href="/q3demotube/delete_video/{{ v.id }}/">[X]</a></td>
</tr>
{% endfor %}
</table>
<p>
    <a href="/q3demotube/add_time/{{ demo.id }}/">Add time</a>
    <a href="/q3demotube/get_images/{{ demo.id }}/">Get Images</a>
    <a href="/q3demotube/get_videos/{{ demo.id }}/">Get Videos</a>
</p>
{% endblock %}

templates/q3demotube/demo_confirm_delete.html
{% extends "q3demotube/baseq3.html" %}

{% block content %}
<form action="/q3demotube/delete_demo/{{ object.id }}/" method="POST">
 <b>Are u sure u want to delete the demo?</b><br/>
 <table>
    <tr> <td>Name:</td> <td>{{ object.name }}</td> </tr>
    <tr> <td>Demo:</td> <td>{{ object.demo.name }}</td> </tr>
    <tr> <td>Category:</td> <td>{{ object.category.name }}</td> </tr>
    <tr> <td>Date:</td> <td>{{ object.time_addet.date }}</td> </tr>
    <tr> <td>#Frags:</td> <td>{{ object.video_set.count }}</td> </tr>
 </table>

<input type="Submit" value="OK">
</form>
{% endblock %}

templates/q3demotube/demo_list.html
{% extends "q3demotube/baseq3.html" %}
{% load sorting_tags %}

{% block page_title %}My Demos{% endblock %}
{% block content %}
<table border="1">
<tr>
    {% table_header headers 'th' %}
</tr>
{% for d in demos  %}
<tr>
    <td> {{ d.name }}</td>
    <td> {{ d.demo.name|slice:":30" }}</td>
    <td> {{ d.category.name }}</td>
    <td> {{ d.time_addet.date }}</td>
    <td> {{ d.user.username }}</td>
    <td> {{ d.video_set.count }}</td>
    <td> <a href="/q3demotube/demo/{{ d.id }}/">[$]</a></td>
    <td> <a href="/q3demotube/delete_demo/{{ d.id }}/">[X]</a></td>
</tr>
{% endfor %}
</table>
{% endblock %}


templates/q3demotube/edit_time.html
{% extends "q3demotube/baseq3.html" %}

{% block page_title %}Edit start and end Time{% endblock %}
{% block content %}
<form action="/q3demotube/edit_time/{{ video.id }}/" method="POST">
 Start: {{ timeForm.start }} End {{ timeForm.end }}
 <input type="Submit" value="Submit">
</form>

<p>
 <b>Double click progress bar to set Start, click to set End!</b> <br/>
 <b>Max video length = 30 sec</b>
</p>



{% if video.has_images %}
    <div id="imgContainer">
	   <img src="{{ MEDIA_URL }}q3/images/{{ video.id }}.jpg" alt="140 images to be precise!" />
    </div>

    <div id="navcontainer">
    <ul id="navlist">
    {% for time, i in images %}
        <li onmouseover="$('#imgContainer img').animate({ left: -440 * {{ i }} }, 2)" id="{{ i }}" onclick="$('input#id_end').val('{{ time }}')" ondblclick="$('input#id_start, #time').val('{{ time }}')">

		<!-- $('img#theImage').attr('src', '{{ MEDIA_URL }}q3/images/{{ demo_id }}-images/{{ video.id }}.{{ i }}.jpg') -->
        {% ifequal videoTime time %}
            <b>||</b>
        {% endifequal  %}
        </li>
    {% endfor %}
    </ul>
    </div>
{% endif %}
{% endblock %}



templates/q3demotube/form.html
<form action="{{ action }}" method="POST">
    {{ form.as_p }}
<input type="Submit" value="Submit">
</form>

templates/q3demotube/my_videos.html
{% extends "q3demotube/baseq3.html" %}

{% block page_title %}My Videos {% endblock %}
{% block content %}
<p>
        <a href='/q3demotube/my_videos/1/' >First</a>
        <a href='/q3demotube/my_videos/{{ page_number|add:"-1" }}/' >Previus</a>
        <label>{{ page_number }}</label> / {{ pages }}
        <a href='/q3demotube/my_videos/{{ page_number|add:"1" }}/' >Next</a>
        <a href='/q3demotube/my_videos/{{ pages }}/' >Last</a>
</p>
{% for video in videos  %}
<p>
    <b><a href="/q3demotube/video/{{ video.id }}/">Name: {{ video.name }}</a></b>
    <b><a href="/q3demotube/video_edit/{{ video.id }}/">Edit</a></b> <br/>
    Demo: {{ video.demo.name }}<br/>
    <a href="/q3demotube/video/{{ video.id }}/"><img width="220" height="110" src="{{ video.thumbnail.url }}"></a>
</p>
{% endfor %}
{% endblock %}

templates/q3demotube/video_confirm_delete.html
{% extends "q3demotube/baseq3.html" %}

{% block content %}
<form action="/q3demotube/delete_video/{{ object.id }}/" method="POST">
 <b>Are u sure u want to delete the Video?</b><br/>
 <table>
    <tr> <td>Name:</td> <td>{{ object.name }}</td> </tr>
    <tr> <td>Demo:</td> <td>{{ object.demo.name }}</td> </tr>
    <tr> <td>Category:</td> <td>{{ object.demo.category.name }}</td> </tr>
    <tr> <td>Description:</td> <td>{{ object.description }}</td> </tr>
    <tr> <td>Time:</td> <td>{{ object.time }}</td> </tr>
    <tr> <td>Time_addet:</td> <td>{{ object.time_addet }}</td> </tr>
 </table>

<input type="Submit" value="OK">
</form>
{% endblock %}

templates/q3demotube/video_edit.html
{% extends "q3demotube/baseq3.html" %}

{% block page_title %}Video edit{% endblock %}
{% block content %}
<p>
<form action="/q3demotube/video_edit/{{ video.id }}/" method="POST">
{{ videoEdit.as_p }}
<input type="Submit" value="Submit"><br/>
</form>

{% endblock %}

templates/q3demotube/videos.html
{% extends "q3demotube/baseq3.html" %}
{% load sorting_tags %}

{% block page_title %}Videos{% endblock %}
{% block content %}
<p>
        <a href='/q3demotube/videos/1/' >First</a>
        <a href='/q3demotube/videos/{{ page_number|add:"-1" }}/' >Previus</a>
        <label>{{ page_number }}</label> / {{ pages }}
        <a href='/q3demotube/videos/{{ page_number|add:"1" }}/' >Next</a>
        <a href='/q3demotube/videos/{{ pages }}/' >Last</a>
</p>
<ul id="sorting_list">
    {% table_header headers 'li' %}
</ul>

<div id="GLOBAL-left-mainframe-course">
{% for video in videos  %}
    <div class="VIDEOS-1grid-box">
        <b><a href="/q3demotube/video/{{ video.id }}/">{{ video.name|slice:":32" }}</a></b><br/>
        <a href="/q3demotube/video/{{ video.id }}/"><img width="220" height="110" src="{{ video.thumbnail.url }}"></a>
    </div>
{% endfor %}
</div>
{% endblock %}