lottery/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    (r'^drawList/$', 'lottery.views.drawList'),
    (r'^history/(?P<page_number>\d+)/$', 'lottery.views.history'),
    (r'^lucky/$', 'lottery.views.lucky'),
    (r'^get_lucky/$', 'lottery.views.get_lucky'),
    (r'^my_lucky/$', 'lottery.views.my_lucky'),
    (r'^delete_lucky/(?P<drawId>\d+)$', 'lottery.views.delete_lucky'),

    (r'^test_login/$', 'simpleLogin.views.test_login'),
    (r'^formSet/$', 'simpleLogin.views.test_form_set'),
    (r'^formSetSubmit/$', 'simpleLogin.views.form_set_submit'),
)

urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^prviDjango/', include('prviDjango.foo.urls')),

    # Uncomment the next line to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line for to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    (r'^polls/', include('polls.urls')),
    (r'^lottery/', include('lottery.urls')),
    (r'^registration/', include('registration.urls')),
    (r'^q3demotube/', include('q3demotube.urls')),
    (r'^threadedcomments/', include('threadedcomments.urls')),
)

lottery/models.py
import re
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Draw(models.Model):
    round_number = models.IntegerField()
    date = models.DateField()
    is_drawen = models.BooleanField()
    value = models.FloatField()
    town = models.CharField(max_length=200)
    is_old = models.BooleanField()
    user = models.ForeignKey(User)

    def __unicode__(self):
        return ", ".join(map(str,[self.round_number, self.date, self.value, self.town]))

    def numbers_list(self):
        return ", ".join(map(str, sorted([i.number for i in self.numbers_set.filter(extra=0)])))

    def extra_number(self):
        try:
            return self.numbers_set.filter(extra=1)[0]
        except:
            return 0

    def has_all(self, s2):
        s1 = set([i.number for i in self.numbers_set.all()])
        #s2 = set(map(int, re.sub("[^\d\,]", "", numbers_string).split(",")))
        return not len(s2 - s1)

    def has_one(self, s2):
        s1 = set([i.number for i in self.numbers_set.all()])
        return (s2 - s1) != s2

class Numbers(models.Model):
    draw = models.ForeignKey(Draw)
    number = models.IntegerField()
    extra = models.BooleanField()

    def __unicode__(self):
        return str(self.number)



lottery/forms.py
from django import forms

class FilterDraw(forms.Form):
    from_date = forms.DateField()
    till_date = forms.DateField()
    is_drawen = forms.BooleanField(required=False)
    logical_and = forms.BooleanField(required=False)
    numbers = forms.CharField(max_length=200)

class LuckyForm(forms.Form):
    lucky = forms.CharField(required=False)
    check = forms.CharField()
    #foo = forms.ModelChoiceField()

lottery/views.py
import datetime
import re
import random
from django import forms
from django.forms.formsets import formset_factory
from django.shortcuts import render_to_response
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.core import serializers
from lottery.forms import *
from lottery.models import Draw


def drawList(req):
    if req.POST:
        form = FilterDraw(req.POST)
        #datetime.date(*map(int,(foo.split("-"))))
        #return HttpResponse(len(form['numbers'].data))
        # DATA
        draws = Draw.objects.filter(date__gte=form['from_date'].data,
                                    date__lte=form['till_date'].data,
                                    is_drawen=[0, 1][form['is_drawen'].data == "on"],
                                    user_id=0)

        #FILTER
        if len(form['numbers'].data):
            s2 = set(map(int, re.sub("[^\d\,]", "", form['numbers'].data).split(",")))
            if form['logical_and'].data == "on":
                draws = [d for d in draws if d.has_all(s2)]
            else:
                draws = [d for d in draws if d.has_one(s2)]

        return render_to_response('lottery/drawList.html', {'form': form, 'draws': draws})
    else:
        form = FilterDraw({ 'from_date':datetime.date(2007, 1, 1), 'till_date':datetime.date.today(),
                            'is_drawen':0, 'logical_and':1})
        return render_to_response('lottery/drawList.html', {'form': form, 'draws': Draw.objects.all()})

def history(req, page_number):
    draws = Draw.objects.all()
    p = Paginator(draws, 20)
    if int(page_number) in p.page_range:
        return render_to_response('lottery/history.html', { 'draws': p.page(page_number).object_list,
                                                            'pages': p.num_pages,
                                                            'page_number': int(page_number)})
    else:
        return HttpResponse("Noup not gona happen %s" % page_number)

@login_required
def lucky(req):
    if req.POST:
        form = LuckyForm(req.POST)
        draws = Draw.objects.filter(user=req.user)
        if form.is_valid():
            s2 = set(map(int, re.sub("[^\d\,]", "", form['check'].data).split(",")))
            draws = [d for d in draws if d.has_all(s2)]
    else:
        form = LuckyForm()
        draws = Draw.objects.filter(user=req.user)

    return render_to_response('lottery/lucky.html', {'form': form, 'draws': draws})

@login_required
def get_lucky(req):
    #CREATE LUCKY
    luckyNumbers = set()
    while len(luckyNumbers) < 8:
        luckyNumbers.add(random.randint(1,39))

    #SAVE LUCKY
    today = datetime.date.today()
    d = Draw(round_number=44, is_drawen=0, value=0, town="", is_old=0, user_id=req.user.id, date=today)
    d.save()
    for i in luckyNumbers:
        d.numbers_set.create(number=i, extra=0)

    d.save()

    #RETURN JSON
    data = serializers.serialize("json", d.numbers_set.all())
    return HttpResponse(data, mimetype="application/javascript") #("[%s]" % ",".join(map(str,luckyNumbers)))

@login_required
def my_lucky(req):
    #GET LUCKY
    luckyNumbers = LuckyForm(req.POST)['lucky'].data
    luckyNumbers = re.sub("[^\d\,]", "", str(luckyNumbers)).split(",")
    luckyNumbers = map(int, luckyNumbers)

    #SAVE LUCKY
    today = datetime.date.today()
    d = Draw(round_number=44, is_drawen=0, value=0, town="", is_old=0, user_id=req.user.id, date=today)
    d.save()
    for i in luckyNumbers:
        d.numbers_set.create(number=i, extra=0)
    d.save()

    #RETURN JSON
    data = serializers.serialize("json", d.numbers_set.all())
    return HttpResponse(data, mimetype="application/javascript")

def delete_lucky(req, drawId):
    Draw.objects.get(pk=drawId).delete()
    return HttpResponse("#%s deleted" % drawId)

@login_required
def test_login(request):
    return HttpResponse('U should see this only if u are logged in ' + str(request.user))



templates/lottery/drawList.html
<form id="form1" name="form1" action="/lottery/drawList/" method="POST">
<table border="1" align="center" cellpadding="3" cellspacing="0" bordercolor="#FFFFFF">
  <tr align="center">
	<td>
        <a href="/lottery/home/" class="style1">Home</a>
        <a href="/lottery/drawList/" class="style1">Now</a>
        <a href="/lottery/history/1/" class="style1">History</a>
        <a href="/lottery/refresh/" class="style1">Refresh</a>
        <a href="/lottery/lucky" class="style1">My lucky</a>
    </td>
  </tr>
  <tr>
	<td align="center">
        From: {{ form.from_date }}
		Till: {{ form.till_date }}
		Is drawen? {{ form.is_drawen }}
    </td>
  </tr>
  <tr align="center">
	<td>
		Numbers: {{ form.numbers }}
		Logical and? {{ form.logical_and }}
    </td>
  </tr>
  <tr align="center">
	<td>
        <input type="Submit" value="Submit">
    </td>
  </tr>
</table>
</form>

<div align="center" id="vsebina">
<table border="1" align="center" cellpadding="3" cellspacing="0" bordercolor="#FFFFFF">
<tr>
    <th><b>Round</b></th>
    <th><b>Date</b></th>
    <th><b>Numbers</b></th>
    <th><b>Num 7</b></th>
    <th><b>Value</b></th>
    <th><b>State</b></th>
</tr>
{% for draw in draws %}
<tr>
    <td> {{ draw.round_number }}</td>
    <td> {{ draw.date }}</td>
    <td> {{ draw.numbers_list }}</td>
    <td> {{ draw.extra_number }}</td>
    <td> {{ draw.value }}</td>
    <td> {{ draw.town }}</td>
</tr>
{% endfor %}
</table>


<style type="text/css">
    <!--
    body {
        background-color: #3779AF;
    }
    body,td,th {
        font-family: Verdana, Arial, Helvetica, sans-serif;
        font-size: 12px;
        color: #FFDB4C;
}
.style1 {color: #FFFFFF}
.style2 {font-size: 10px;}
-->
</style>

templates/lottery/formSet.html
<form action="/lottery/formSetSubmit/" method="POST">
<table>
    {{ formSet }}
</table>
<input type="Submit" value="Submit">
</form>

templates/lottery/history.html
<form id="form1" name="form1" action="/lottery/history/" method="POST">
<table border="1" align="center" cellpadding="3" cellspacing="0" bordercolor="#FFFFFF">
  <tr align="center">
	<td>
        <a href="/lottery/home/" class="style1">Home</a>
        <a href="/lottery/drawList/" class="style1">Now</a>
        <a href="/lottery/history/1/" class="style1">History</a>
        <a href="/lottery/refresh/" class="style1">Refresh</a>
        <a href="/lottery/lucky" class="style1">My lucky</a>
    </td>
  </tr>
</table>
<p align="center">
        <a href='/lottery/history/1/' >First</a>
        <a href='/lottery/history/{{ page_number|add:"-1" }}/' >Previus</a>
        <input type="text" name="stran" id="stran" size="3" value="{{ page_number }}" onChange=""> / {{ pages }}
        <a href='/lottery/history/{{ page_number|add:"1" }}/' >Next</a>
        <a href='/lottery/history/{{ pages }}/' >Last</a>
</p>
</form>

<table border="1" align="center" cellpadding="3" cellspacing="0" bordercolor="#FFFFFF">
<tr>
    <th><b>Round</b></th>
    <th><b>Date</b></th>
    <th><b>Numbers</b></th>
    <th><b>Num 7</b></th>
    <th><b>Value</b></th>
    <th><b>State</b></th>
</tr>
{% for draw in draws %}
<tr>
    <td> {{ draw.round_number }}</td>
    <td> {{ draw.date }}</td>
    <td> {{ draw.numbers_list }}</td>
    <td> {{ draw.extra_number }}</td>
    <td> {{ draw.value }}</td>
    <td> {{ draw.town }}</td>
</tr>
{% endfor %}
</table>


<style type="text/css">
    <!--
    body {
        background-color: #3779AF;
    }
    body,td,th {
        font-family: Verdana, Arial, Helvetica, sans-serif;
        font-size: 12px;
        color: #FFDB4C;
}
.style1 {color: #FFFFFF}
a {color: #FFFFFF}
.style2 {font-size: 10px;}
-->
</style>

templates/lottery/lucky.html
<html>
<script src="http://localhost/js/lib/jquery-1.2.6.js" type="text/javascript"></script>
<script src="http://localhost/js/lib/jquery-create.js" type="text/javascript"></script>
<form action="/lottery/lucky/" method="POST">
<table border="1" align="center" cellpadding="3" cellspacing="0" bordercolor="#FFFFFF">
  <tr align="center">
	<td>
        <a href="/lottery/home/" class="style1">Home</a>
        <a href="/lottery/drawList/" class="style1">Now</a>
        <a href="/lottery/history/1/" class="style1">History</a>
        <a href="/lottery/refresh/" class="style1">Refresh</a>
        <a href="/lottery/lucky" class="style1">My lucky</a>
    </td>
  </tr>
  <tr>
	<td align="center">
        Lucky: {{ form.lucky }} <input type="Button" value="Get Lucky" onClick="get_lucky()"> <input type="Button" onClick="my_lucky($('#id_lucky').val())" value="My Lucky"><br/>
        {{ form.check }} <input type="Submit" value="Check">
    </td>
  </tr>
</table>
</form>
<script type="text/javascript">
//==== ==== ==== ====
//DELETE LUCKY
//==== ==== ==== ====
function delete_lucky(id) {
	$.get('/lottery/delete_lucky/' + id, {}, function(txt) {
		txt = txt.split(" ")
		$(txt[0]).remove()
	 })
}

function rate_video(rated) {
 $.post("/q3demotube/rate_video/",
       {video:"43", rate:rated},
       function(txt)
         {
         console.log(data);
         });
}

//==== ==== ==== ====
//GET LUCKY
//==== ==== ==== ====
function get_lucky()	{
$.getJSON("/lottery/get_lucky/", { }, function(json){
        n = insert_row(json)
        $('#id_lucky').val(n)
	});
}

//==== ==== ==== ====
//MY LUCKY
//==== ==== ==== ====
function my_lucky(string)	{

 $.ajax({
   type: "POST",
   url: "/lottery/my_lucky/",
   data: { lucky:string },
   dataType: "json",
   success: function(json){
     insert_row(json);
   }
 });

}
//==== ==== ==== ====
//INSERT NEW ROW
//==== ==== ==== ====
function insert_row(draws)	{
	id = draws[0].fields.draw
	luckyNumbers = [draws[i].fields.number for(i in draws)]
	console.log("luckyNumbers: " + luckyNumbers)
	console.log("Will create and insert row!!" )
    newRow = $.create(
	    "tr", {"id":id}, [
	        "td", {}, [" "],
	        "td", {}, [" "],
			"td", {}, [luckyNumbers.join(", ")],
			"td", {}, ["input", {"type":"button", "onclick":"delete_lucky("+ id +")", "value":"x",  "width":"7", "height":"7"}, []]
			]
	)
	$("#luckyTable tbody").append(newRow)
	return luckyNumbers
}
</script>
<div align="center" id="vsebina">
<table id="luckyTable" border="1" align="center" cellpadding="3" cellspacing="0" bordercolor="#FFFFFF">
<tr>
    <th><b>Round</b></th>
    <th><b>Date</b></th>
    <th><b>Numbers</b></th>
    <th></th>
</tr>
{% for draw in draws %}
<tr id="{{ draw.id }}">
    <td> {{ draw.round_number }}</td>
    <td> {{ draw.date }}</td>
    <td> {{ draw.numbers_list }}</td>
    <td> <input type="button" onclick="delete_lucky('{{ draw.id }}')" value="x"  width="5" height="5"></td>
</tr>
{% endfor %}
</table>

</html>
<style type="text/css">
    <!--
    body {
        background-color: #3779AF;
    }
    body,td,th {
        font-family: Verdana, Arial, Helvetica, sans-serif;
        font-size: 12px;
        color: #FFDB4C;
}
.style1 {color: #FFFFFF}
.style2 {font-size: 10px;}
-->
</style>